'use strict';
$(document).ready(function(){
  $('.checkbox1').click(function(){
    $('.checkbox1').css('width','50px');
    $('.checkbox1').css('height','50px');
    $('.checkbox1').css('background-position','-102px','-70px');
    $('.checkbox1').css('margin-left','2%');
    $('.checkbox2').css('width','50px');
    $('.checkbox2').css('height','50px');
    $('.checkbox2').css('background-position','-40px','-70px');
    $('.checkbox2').css('margin-left','2%');
  });
  $('.checkbox2').click(function(){
    $('.checkbox2').css('width','50px');
    $('.checkbox2').css('height','50px');
    $('.checkbox2').css('background-position','-102px','-70px');
    $('.checkbox2').css('margin-left','2%');
    $('.checkbox1').css('width','50px');
    $('.checkbox1').css('height','50px');
    $('.checkbox1').css('background-position','-40px','-70px');
    $('.checkbox1').css('margin-left','2%');
  });
  $('.radio1').click(function(){
    $('.radio1').css('width','50px');
    $('.radio1').css('height','50px');
    $('.radio1').css('background-position','-220px','-70px');
    $('.radio1').css('margin-left','2%');
    $('.radio2').css('width','50px');
    $('.radio2').css('height','50px');
    $('.radio2').css('background-position','-160px','-70px');
    $('.radio2').css('margin-left','2%');
  });
  $('.radio2').click(function(){
    $('.radio2').css('width','50px');
    $('.radio2').css('height','50px');
    $('.radio2').css('background-position','-220px','-70px');
    $('.radio2').css('margin-left','2%');
    $('.radio1').css('width','50px');
    $('.radio1').css('height','50px');
    $('.radio1').css('background-position','-160px','-70px');
    $('.radio1').css('margin-left','2%');
  });
  $('.button1').click(function(){
    $('.button1').css('width','35%');
    $('.button1').css('background-color','#4e4848');
    $('.button1').css('color','white');
    $('.button1').css('font-weight','bold');
    $('.button1').css('border-style','none');
    $('.button1').css('display','inline-block');
    $('.button1').css('margin-left','4%');
    $('.button2').css('width','35%');
    $('.button2').css('background-color','#c3c3c3');
    $('.button2').css('color','black');
    $('.button2').css('font-weight','bold');
    $('.button2').css('border-style','none');
    $('.button2').css('display','inline-block');
    $('.button2').css('margin-left','2%');
  });
  $('.button2').click(function(){
    $('.button1').css('width','35%');
    $('.button1').css('background-color','#c3c3c3');
    $('.button1').css('color','black');
    $('.button1').css('font-weight','bold');
    $('.button1').css('border-style','none');
    $('.button1').css('display','inline-block');
    $('.button1').css('margin-left','2%');
    $('.button2').css('width','35%');
    $('.button2').css('background-color','#4e4848');
    $('.button2').css('color','white');
    $('.button2').css('font-weight','bold');
    $('.button2').css('border-style','none');
    $('.button2').css('display','inline-block');
    $('.button2').css('margin-left','4%');
  });

});
